
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='medoo',
    version='0.0.8',
    description='A lightweight database framework for python',
    python_requires='==3.*,>=3.6.0',
    project_urls={"homepage": "https://github.com/pwwang/pymedoo",
                  "repository": "https://github.com/pwwang/pymedoo"},
    author='pwwang',
    author_email='pwwang@pwwang.com',
    license='MIT',
    packages=['medoo', 'medoo.database'],
    package_dir={"": "."},
    package_data={"medoo": ["*.bak"]},
    install_requires=[
        'six==1.*,>=1.12.0; python_version == "2.7.*" and python_version >= "2.7.0"'],
    extras_require={"dev": ["autopep8==1.*,>=1.5.3", "black==19.*,>=19.10.0",
                            "pytest", "pytest-cov", "tablib==0.*,>=0.13.0"]},
)
